# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021 Intel Corporation
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
    spec:
      containers:
      - env:
        - name: PORT
          value: {{ .Values.frontend.server.port | quote }}
        - name: DISABLE_TRACING
          value: "1"
        - name: DISABLE_PROFILER
          value: "1"
        - name: DISABLE_DEBUGGER
          value: "1"
        - name: PRODUCT_CATALOG_SERVICE_ADDR
          value: productcatalogservice:{{ .Values.frontend.server.productcatalogserviceport }}
        - name: CURRENCY_SERVICE_ADDR
          value: currencyservice:{{ .Values.frontend.server.currencyserviceport }}
        - name: CART_SERVICE_ADDR
          value: cartservice:{{ .Values.frontend.server.cartserviceport }}
        - name: RECOMMENDATION_SERVICE_ADDR
          value: recommendationservice:{{ .Values.frontend.server.recommendationserviceport }}
        - name: SHIPPING_SERVICE_ADDR
          value: shippingservice:{{ .Values.frontend.server.shippingserviceiport }}
        - name: CHECKOUT_SERVICE_ADDR
          value: checkoutservice:{{ .Values.frontend.server.checkoutserviceport }}
        - name: AD_SERVICE_ADDR
          value: adservice:{{ .Values.frontend.server.adserviceport }}
        image: {{ .Values.frontend.server.image.repository }}:{{ .Values.frontend.server.image.tag | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.frontend.server.image.pullPolicy }}
        livenessProbe:
          httpGet:
            httpHeaders:
            - name: Cookie
              value: shop_session-id=x-liveness-probe
            path: /_healthz
            port: {{ .Values.frontend.server.port }}
          initialDelaySeconds: 10
        name: server
        ports:
        - containerPort: {{ .Values.frontend.server.port }}
        readinessProbe:
          httpGet:
            httpHeaders:
            - name: Cookie
              value: shop_session-id=x-readiness-probe
            path: /_healthz
            port: {{ .Values.frontend.server.port }}
          initialDelaySeconds: 10
        resources: {{- toYaml .Values.frontend.server.resources | nindent 10 }}
      serviceAccountName: default
