# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021 Intel Corporation
productcatalogservice:
  ports:
  - name: grpc
    port: 3550
    targetPort: 3550
  server:
    port: 3550
    image:
      repository: gcr.io/google-samples/microservices-demo/productcatalogservice
      tag: "v0.3.9"
      pullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 200m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 64Mi
  type: ClusterIP
