# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2017 Amdocs, Bell Canada
# Copyright (c) 2022 Intel Corporation

apiVersion: v2
description: Common templates for other EMCO charts
name: common
version: 1.0.0