# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021 Intel Corporation
apiVersion: v2
name: emailservice
description: A Helm chart for emailservice
type: application
version: 0.1.0
appVersion: "v0.3.9"
