# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021 Intel Corporation

image:
    repository: <myrepository.example.com>/app/my-public-httptest-server
    tag: "1.4"
    pullPolicy: Always

service:
    name: http-service
    type: LoadBalancer
    tcpPort: 30083
    nameOfPort: webPort
    annotations: {}
    labels: {}
    clusterIP: ""

resources:
    limits:
        cpu: 100m
        memory: 128Mi
    requests:
        cpu: 100m
        memory: 128Mi
