    ProjectName: proj1
    ClusterProvider: provider1
    Cluster1: cluster1
    ClusterLabel: edge-cluster
    ClusterLabelNetworkPolicy: networkpolicy-supported
    Cluster1Ref: cluster1-ref
    LogicalCloud: lc1
    AdminCloud: admin-lc
    PrivilegedCloud: privileged-lc
    StandardCloud: standard-lc
    PrivilegedNamespace: privileged-lc-ns
    StandardNamespace: standard-lc-ns
    ClusterQuota: quota1
    StandardPermission: standard-permission
    PrivilegedPermission1: privileged-permission-primary
    PrivilegedPermission2: privileged-permission-kube-system
    PrivilegedPermission3: privileged-permission-cluster
    CompositeApp: prometheus-collectd-composite-app
    App1: kube-prometheus-stack
    App2: collectd
    App3: operator
    App4: http-client
    App5: http-server
    AppMonitor: monitor
    HelmApp1: output/kube-prometheus-stack.tar.gz
    HelmApp2: output/collectd.tar.gz
    HelmApp3: output/operator.tar.gz
    HelmApp4: output/http-client.tar.gz
    HelmApp5: output/http-server.tar.gz
    HelmAppMonitor: output/monitor.tar.gz
    HelmAppFirewall: output/firewall.tar.gz
    HelmAppPacketgen: output/packetgen.tar.gz
    HelmAppSink: output/sink.tar.gz
    ProfileFw: output/profile.tar.gz
    ProfileApp1: output/kube-prometheus-stack_profile.tar.gz
    ProfileApp2: output/collectd_profile.tar.gz
    ProfileApp3: output/operator_profile.tar.gz
    ProfileApp4: output/http-client-profile.tar.gz
    ProfileApp5: output/http-server-profile.tar.gz
    CompositeProfile: collection-composite-profile
    GenericPlacementIntent: collection-placement-intent
    DeploymentIntent: collection-deployment-intent-group
    CompositeAppGac: gac-composite-app
    GacIntent: collectd-gac-intent
    CompositeAppDtc: dtc-composite-app
    DtcIntent: collectd-dtc-intent
    CompositeAppMonitor: monitor-composite-app
    ConfigmapFile: info.json
