# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020 Intel Corporation

---
#creating composite app entry
version: emco/v2
resourceContext:
  anchor: projects/{{ .ProjectName }}/composite-apps
metadata :
  name: {{ .CompositeApp }}
spec:
  compositeAppVersion: v1

{{- range $index, $app := .Applist }}
---
#adding app to the composite app
version: emco/v2
resourceContext:
  anchor: projects/{{ $.ProjectName }}/composite-apps/{{ $.CompositeApp }}/v1/apps
metadata :
  name: {{ $app.Name }}
file:
  {{ $.PackagesPath }}/{{ $app.Name }}.tar.gz
{{- end }}

---
#creating composite profile entry
version: emco/v2
resourceContext:
  anchor: projects/{{ .ProjectName }}/composite-apps/{{ .CompositeApp }}/v1/composite-profiles
metadata :
  name: {{ .CompositeProfile }}

{{- range $index, $app := .Applist }}
---
#adding app profiles to the composite profile
version: emco/v2
resourceContext:
  anchor: projects/{{ $.ProjectName }}/composite-apps/{{ $.CompositeApp }}/v1/composite-profiles/{{ $.CompositeProfile }}/profiles
metadata :
  name: {{ $app.Name }}-profile
spec:
  app: {{ $app.Name }}
file:
  {{ $.PackagesPath }}/{{ $app.Name }}_profile.tar.gz
{{- end }}

---
#create deployment intent group
version: emco/v2
resourceContext:
  anchor: projects/{{ .ProjectName }}/composite-apps/{{ .CompositeApp }}/v1/deployment-intent-groups
metadata :
  name: {{ .DeploymentIntent }}
  description: "description"
spec:
  compositeProfile: {{ .CompositeProfile }}
  version: r1
  logicalCloud: {{ .AdminCloud }}
  overrideValues: []

---
#create intent in deployment intent group
version: emco/v2
resourceContext:
  anchor: projects/{{ .ProjectName }}/composite-apps/{{ .CompositeApp }}/v1/deployment-intent-groups/{{ .DeploymentIntent }}/intents
metadata :
  name: {{ .Intent }}
spec:
  intent:
    genericPlacementIntent: {{ .GenericPlacementIntent }}

---
#create the generic placement intent
version: emco/v2
resourceContext:
  anchor: projects/{{ .ProjectName }}/composite-apps/{{ .CompositeApp }}/v1/deployment-intent-groups/{{ .DeploymentIntent }}/generic-placement-intents
metadata :
  name: {{ .GenericPlacementIntent }}
spec:
  logicalCloud: {{ .AdminCloud }}

{{- range $index, $app := .Applist }}
---
#add the app placement intent to the generic placement intent
version: emco/v2
resourceContext:
  anchor: projects/{{ $.ProjectName }}/composite-apps/{{ $.CompositeApp }}/v1/deployment-intent-groups/{{ $.DeploymentIntent }}/generic-placement-intents/{{ $.GenericPlacementIntent }}/app-intents
metadata:
  name: {{ $app.Name }}-placement-intent
spec:
  app: {{ $app.Name }}
  intent:
    allOf:
    {{- range $index1, $cluster := $app.Cluster }}
    - clusterProvider: {{ $.ClusterProvider }}
      cluster: {{ $cluster }}
    {{- end }}
{{- end }}

