# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021 Intel Corporation
apiVersion: apps/v1
kind: Deployment
metadata:
  name: emailservice
spec:
  selector:
    matchLabels:
      app: emailservice
  template:
    metadata:
      labels:
        app: emailservice
    spec:
      containers:
      - env:
        - name: PORT
          value: {{ .Values.emailservice.server.port | quote }}
        - name: DISABLE_PROFILER
          value: "1"
        image: {{ .Values.emailservice.server.image.repository }}:{{ .Values.emailservice.server.image.tag | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.emailservice.server.image.pullPolicy }}
        livenessProbe:
          exec:
            command:
            - /bin/grpc_health_probe
            - -addr=:{{ .Values.emailservice.server.port }}
          initialDelaySeconds: 30
          periodSeconds: 5
        name: server
        ports:
        - containerPort: {{ .Values.emailservice.server.port }}
        readinessProbe:
          exec:
            command:
            - /bin/grpc_health_probe
            - -addr=:{{ .Values.emailservice.server.port }}
          initialDelaySeconds: 30
          periodSeconds: 5
        resources: {{- toYaml .Values.emailservice.server.resources | nindent 10 }}
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
