# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020 Intel Corporation

---
#creating collection composite app entry
version: emco/v2
resourceContext:
  anchor: projects/{{.ProjectName}}/composite-apps
metadata :
  name: {{.CompositeApp}}
  description: test
spec:
  compositeAppVersion: v1

---
#adding app to the composite app
version: emco/v2
resourceContext:
  anchor: projects/{{.ProjectName}}/composite-apps/{{.CompositeApp}}/v1/apps
metadata :
  name: {{.App1}}
  description: "description for app"
file:
  {{.HelmApp1}}

---
#adding app to the composite app
version: emco/v2
resourceContext:
  anchor: projects/{{.ProjectName}}/composite-apps/{{.CompositeApp}}/v1/apps
metadata :
  name: {{.App2}}
  description: "description for app"
file:
  {{.HelmApp2}}

---
#creating collection composite profile entry
version: emco/v2
resourceContext:
  anchor: projects/{{.ProjectName}}/composite-apps/{{.CompositeApp}}/v1/composite-profiles
metadata :
  name: {{.CompositeProfile}}
  description: test

---
#adding app profiles to the composite profile
version: emco/v2
resourceContext:
  anchor: projects/{{.ProjectName}}/composite-apps/{{.CompositeApp}}/v1/composite-profiles/{{.CompositeProfile}}/profiles
metadata :
  name: profile1
  description: test
spec:
  app: {{.App1}}
file:
  {{.ProfileApp1}}

---
#adding app profiles to the composite profile
version: emco/v2
resourceContext:
  anchor: projects/{{.ProjectName}}/composite-apps/{{.CompositeApp}}/v1/composite-profiles/{{.CompositeProfile}}/profiles
metadata :
  name: profile2
  description: test
spec:
  app: {{.App2}}
file:
  {{.ProfileApp2}}

---
#create deployment intent group
version: emco/v2
resourceContext:
  anchor: projects/{{.ProjectName}}/composite-apps/{{.CompositeApp}}/v1/deployment-intent-groups
metadata :
  name: {{.DeploymentIntent}}
  description: "description"
spec:
  compositeProfile: {{.CompositeProfile}}
  version: r1
  logicalCloud: {{.AdminCloud}}
  overrideValues: []

---
#create intent in deployment intent group
version: emco/v2
resourceContext:
  anchor: projects/{{.ProjectName}}/composite-apps/{{.CompositeApp}}/v1/deployment-intent-groups/{{.DeploymentIntent}}/intents
metadata :
  name: collection-deployment-intent
  description: "description"
spec:
  intent:
    genericPlacementIntent: {{.GenericPlacementIntent}}

---
#create the generic placement intent 
version: emco/v2
resourceContext:
  anchor: projects/{{.ProjectName}}/composite-apps/{{.CompositeApp}}/v1/deployment-intent-groups/{{.DeploymentIntent}}/generic-placement-intents
metadata :
  name: {{.GenericPlacementIntent}}
  description: "description for app"
spec:
  logicalCloud: {{.AdminCloud}}

---
#add the prometheus app placement intent to the generic placement intent
version: emco/v2
resourceContext:
  anchor: projects/{{.ProjectName}}/composite-apps/{{.CompositeApp}}/v1/deployment-intent-groups/{{.DeploymentIntent}}/generic-placement-intents/{{.GenericPlacementIntent}}/app-intents
metadata:
  name: prometheus-placement-intent
  description: description of placement_intent
spec:
  app: {{.App1}}
  intent:
    allOf:
    - clusterProvider: {{.ClusterProvider}}
      clusterLabel: {{.ClusterLabel}}

---
#add the collectd app placement intent to the generic placement intent
version: emco/v2
resourceContext:
  anchor: projects/{{.ProjectName}}/composite-apps/{{.CompositeApp}}/v1/deployment-intent-groups/{{.DeploymentIntent}}/generic-placement-intents/{{.GenericPlacementIntent}}/app-intents
metadata:
  name: collectd-placement-intent
  description: description of placement_intent
spec:
  app: {{.App2}}
  intent:
    allOf:
    - clusterProvider: {{.ClusterProvider}}
      clusterLabel: {{.ClusterLabel}}

---
#Approve
version: emco/v2
resourceContext:
  anchor: projects/{{.ProjectName}}/composite-apps/{{.CompositeApp}}/v1/deployment-intent-groups/{{.DeploymentIntent}}/approve

---
#Instantiate
version: emco/v2
resourceContext:
  anchor: projects/{{.ProjectName}}/composite-apps/{{.CompositeApp}}/v1/deployment-intent-groups/{{.DeploymentIntent}}/instantiate
